first_project/first_app/urls.py
from django.urls import path
from first_app import views

app_name = 'first_app'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('other/', views.other, name='other'),
    path('relative/', views.relative, name='relative'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='user_login'),
]

first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path, include
from first_app import views

urlpatterns = [
    path('first_app/', include('first_app.urls')),
    path('admin/', admin.site.urls),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special'),

]

first_project/first_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Topic(models.Model):
    top_name = models.CharField(max_length=264, unique=True)

    def __str__(self):
        return self.top_name


class Webpage(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length=264, unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return str(self.name)


class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage, on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return str(self.date)


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank=True)
    profile_pic =  models.ImageField(upload_to='profile_pics', blank = True)

    def __str__(self):
        return self.user.username

first_project/first_app/forms.py
from django import forms
from django.contrib.auth.models import User
from first_app.models import UserProfileInfo
from django.core import validators


#
# def check_for_z(value):
#     if value[0].lower() != 'z':
#         raise forms.ValidationError("Name should start with Z")


class FormName(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    verify_email = forms.EmailField(label='Enter your email again:')
    text = forms.CharField(widget=forms.Textarea)

    # botcatcher = forms.CharField(required=False,
    #                              widget=forms.HiddenInput,
    #                              validators=[validators.MaxLengthValidator(0)])

    def clean(self):
        all_clean_data = super().clean()
        email = all_clean_data['email']
        vmail = all_clean_data['verify_email']

        if email != vmail:
            raise forms.ValidationError("Emails don't match")

    # def clean_botcatcher(self):
    #     botcatcher = self.cleaned_data['botcatcher']
    #     if len(botcatcher) > 0:
    #         raise forms.ValidationError("Gotcha Bot")
    #     return botcatcher


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

first_project/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from first_app.models import Topic, Webpage, AccessRecord
from first_app.forms import UserForm, UserProfileInfoForm
from . import forms
import os

from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout


# Create your views here.

def index(request):
    # context_dict = {'text':'hello world','number':100}
    return render(request, 'first_app/index.html')


def other(request):
    return render(request, 'first_app/other.html')


def relative(request):
    return render(request, 'first_app/relative_url_templates.html')


def form_name_view(request):
    form = forms.FormName()
    if request.method == 'POST':
        form = forms.FormName(request.POST)

        if form.is_valid():
            print("VALIDATION SUCCESS")
            print("NAME: " + form.cleaned_data['name'])
            print("EMAIL: " + form.cleaned_data['email'])
            print("TEXT: " + form.cleaned_data['text'])
    return render(request, 'first_app/form_page.html', {'form': form})


@login_required
def special(request):
    return HttpResponse("You are logged in")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('first_app:index'))


def register(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'first_app/registration.html', {'user_form': user_form,
                                                           'profile_form': profile_form,
                                                           'registered': registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('first_app:index'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("Someone tried to login and failed")
            print("Username: {} and Password: {}".format(username, password))
            return HttpResponse("Invalid login details")
    else:
        return render(request, 'first_app/login.html')

first_project/templates/first_app/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <title>Django Level 4</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    </head>
</html>
<body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'first_app:index' %}">DJANGO</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'first_app:register' %}">Register</a></li>

            {% if user.is_authenticated %}
                <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
            {%else%}
                <li><a class="navbar-link" href="{% url 'first_app:user_login' %}">Login</a></li>
            {% endif %}

        </ul>
      </div>
    </nav>

    <div class="container">

    {% block body_block %}

    {% endblock %}
    </div>
</body>

first_project/templates/first_app/form_page.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <title>Forms</title>
        <link rel="stylesheet" href="{%  static 'css/mystyle.css' %}"/>
    </head>
</html>
<body>
    <h1>Fill out the form!</h1>
    <div>
        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Submit">
        </form>
    </div>

</body>

first_project/templates/first_app/index.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
{% block body_block %}
    <div class = "jumbotron">
        <h1>Django level 5</h1>
    </div>
{% endblock %}

first_project/templates/first_app/login.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
{% block body_block %}
    <div class = "jumbotron">
        <h1>Login Here</h1>
        <form action="{% url 'first_app:user_login' %}" method = post>
            {% csrf_token %}
            <label for="username">Username</label>
            <input type="text" name="username" placeholder="Enter your ID">
            <label for="password">Password</label>
            <input type="password" name="password">
            <input type="submit" name="" value="Login">
        </form>
    </div>
{% endblock %}

first_project/templates/first_app/other.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
    {% block body_block %}
        <h1>Welcome to other</h1>
    {% endblock %}
</body>

first_project/templates/first_app/registration.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
{% block body_block %}
    <div class = "jumbotron">
        {% if registered %}
            <h1>Thank you for registering</h1>
        {% else %}
            <h1>Register Here</h1>
            <h3>Fill out the form:</h3>

            <form enctype="multipart/form-data" method="post">
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                <input type="submit" name="" value="Register">
            </form>
        {% endif %}
    </div>
{% endblock %}

first_project/templates/first_app/relative_url_templates.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <title>Django Level 4</title>
        <link rel="stylesheet" href="{%  static 'css/mystyle.css' %}"/>
    </head>
</html>
<body>
    <h1>Welcome to relative url templates</h1>
    <a href="{% url 'first_app:other' %}">The other page</a>
    <a href="{% url 'admin:index' %}">admin</a>
</body>